[package]
name = "exploreasl_gui"
version = "0.1.2"
description = "A Tauri App"
authors = ["you"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "exploreasl_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.11.3", features = ["image-png"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-os = "2"
tauri-plugin-store = "2"
tauri-plugin-log = "2.9.0"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
regex = "1.12.3"
tauri-plugin-clipboard-manager = "2.3.2"
notify = "8.2.0"
num_cpus = "1"
sha2 = "0.10"
tempfile = "3"
csv = "1.4.0"
calamine = "0.35.0"
libc = "0.2"
strsim = "0.11.1"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.31.3", features = ["signal"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_System_Threading", "Win32_Foundation", "Win32_System_Console", "Win32_System_Memory", "Win32_System_SystemInformation", "Win32_Storage_FileSystem"] }
